# Generated by Django 2.1.7 on 2019-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_auto_20190324_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='hydrocarbons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diet',
            name='products',
            field=models.ManyToManyField(to='dietapp.Product'),
        ),
    ]
