# Generated by Django 2.1.7 on 2019-03-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0003_auto_20190327_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='default_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='portion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.Product'),
        ),
    ]
