# Generated by Django 2.1.7 on 2019-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0004_auto_20190330_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='products',
        ),
        migrations.AddField(
            model_name='diet',
            name='portions',
            field=models.ManyToManyField(to='dietapp.Portion'),
        ),
    ]
