# Generated by Django 2.1.7 on 2019-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0005_auto_20190330_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='portions',
        ),
        migrations.AddField(
            model_name='diet',
            name='products',
            field=models.ManyToManyField(to='dietapp.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='Portion',
        ),
    ]
