# Generated by Django 2.1.7 on 2019-03-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0006_auto_20190331_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_size',
        ),
        migrations.AddField(
            model_name='product',
            name='minerals',
            field=models.IntegerField(default=0),
        ),
    ]
