# Generated by Django 2.1.7 on 2019-05-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0007_auto_20190331_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='default_price',
        ),
    ]
